AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  GitProviderType:
    Type: String
    Default: "GitHub"
  MainGitBranch:
    Type: String
    Default: "main"
  SamTemplate:
    Type: String
    Default: "template.yaml"
  TestingRegion:
    Type: String
    Default: "us-east-1"
  TestingStackName:
    Type: String
    Default: "sam-app-hello-custom"
  FeatureGitBranch:
    Type: String
    Default: "main"
  CodeStarConnectionArn:
    Type: String
    Default: ""
  # TestingPipelineExecutionRole:
  #   Type: String
  #   Default: "arn:aws:iam::038462753284:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-kjUnsYW3lwU5"
  # TestingCloudFormationExecutionRole:
  #   Type: String
  #   Default: "arn:aws:iam::038462753284:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-49OvZBvH2N7s"
  # TestingArtifactBucket:
  #   Type: String
  #   Default: "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-rqd3axx84w38"


Resources:
  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "MyGitHubPipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: sam-app-hello-custom-artifacts
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: "Cool233777"
                Repo: "sam-project-hello-custom"
                Branch: "main"
                OAuthToken: "{{resolve:secretsmanager:TokenDeMiGit}}"
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: CodeDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName: "sam-app-hello-custom-deploy"
                DeploymentGroupName: "MiGrupoDeDespliegue"
              RunOrder: 1


  CodePipelineRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CodePipelineExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                  - codepipeline.amazonaws.com
              Action: 
                - "sts:AssumeRole"
        Policies:
          - PolicyName: CodePipelinePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:GetObject"
                    - "s3:PutObject"
                    - "s3:ListBucket"
                  Resource: 
                    - "arn:aws:s3:::sam-app-hello-custom-artifacts"
                    - "arn:aws:s3:::sam-app-hello-custom-artifacts/*"
                - Effect: Allow
                  Action:
                    - "codebuild:StartBuild"
                    - "codebuild:BatchGetBuilds"
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - "iam:PassRole"
                  Resource: "*"



  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "sam-app-hello-custom-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildExecutionRole-Custom
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:GetBucketLocation"
                Resource: !Sub "arn:aws:s3:::sam-app-hello-custom-artifacts/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource: "*"