AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  GitProviderType:
    Type: String
    Default: "GitHub"
  MainGitBranch:
    Type: String
    Default: "main"
  SamTemplate:
    Type: String
    Default: "template.yaml"
  TestingRegion:
    Type: String
    Default: "us-east-1"
  TestingStackName:
    Type: String
    Default: "sam-app-hello-custom"
  # TestingPipelineExecutionRole:
  #   Type: String
  #   Default: "arn:aws:iam::038462753284:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-kjUnsYW3lwU5"
  # TestingCloudFormationExecutionRole:
  #   Type: String
  #   Default: "arn:aws:iam::038462753284:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-49OvZBvH2N7s"
  # TestingArtifactBucket:
  #   Type: String
  #   Default: "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-rqd3axx84w38"


Resources:
  CodeStarConnection:
    Condition: CreateConnection
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: CustomGitConnection
      ProviderType: 
        Type: String
        Default: "GitHub"
  Pipeline:
    Properties:
      ArtifactStore:
        Location: "sam-app-hello-custom-artifacts"
        Type: S3
      #RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubConnection
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !If [CreateConnection, "", ""]
                FullRepositoryId: "cool233777/sam-project-hello-custom"
                BranchName: "main"
              OutputArtifacts:
                - Name: SourceCodeAsZip
              RunOrder: 1
        # - Name: ActualizarPipeline
        #   Actions:
        #     - Name: CreateChangeSet
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Provider: CloudFormation
        #         Version: "1"
        #       Configuration:
        #         ActionMode: CHANGE_SET_REPLACE
        #         RoleArn: !GetAtt PipelineStackCloudFormationExecutionRole.Arn
        #         StackName: !Ref AWS::StackName
        #         ChangeSetName: !Sub ${AWS::StackName}-ChangeSet
        #         TemplatePath: SourceCodeAsZip::codepipeline.yaml
        #         Capabilities: CAPABILITY_NAMED_IAM
        #         ParameterOverrides: !Sub |
        #           {
        #             "FeatureGitBranch": "${FeatureGitBranch}",
        #             "CodeStarConnectionArn": "${CodeStarConnectionArn}"
        #           }
        #       InputArtifacts:
        #         - Name: SourceCodeAsZip
        #       RunOrder: 1
        #     - Name: ExecuteChangeSet
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Provider: CloudFormation
        #         Version: "1"
        #       Configuration:
        #         ActionMode: CHANGE_SET_EXECUTE
        #         RoleArn: !GetAtt PipelineStackCloudFormationExecutionRole.Arn
        #         StackName: !Ref AWS::StackName
        #         ChangeSetName: !Sub ${AWS::StackName}-ChangeSet
        #       OutputArtifacts:
        #         - Name: !Sub ${AWS::StackName}ChangeSet
        #       RunOrder: 2
