AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-hello-custom

  Sample SAM Template for sam-app-hello-custom

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  RDSConnectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rds_connect.lambda_handler
      Runtime: python3.13
      CodeUri: hello_world/src/
      Environment:
        Variables:
          ENCRYPTED_RDS_CREDENTIALS: "AQICAHj+liaqPgt0r3m0w56wvwx5sdne9GFt1aRMYWBdmnc8swEhIln3h/nLLgxAPyPToALZAAAA+TCB9gYJKoZIhvcNAQcGoIHoMIHlAgEAMIHfBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGIJ8EBgfgzG2aeAqwIBEICBsf9K+1UVNkDsYOG2wQ48os1Hv5hIyFhX5BsKdhsUFSCzRgp+Fxp1UT/trKh0d/SJ0S9y6e0qRMNPIlYoNu5OO+cjJXfhhBGkaKhdHeeA0Nbzz011ZlyZEcuayymSRAeFNptItLefXJVZsYaKOxVAGN1+CXla1e2etdwE/MvkT8wiWgQuJl5tvptOBTc7J1lkOy5TgwdWy6h19it92yGq+Pny0Wj9YPAZRg9D4bf5N2MSFg=="
          KMS_KEY_ARN: "arn:aws:kms:us-east-1:038462753284:key/e7f712a6-2273-4cfb-a97b-e5eac6d64c68"
      Timeout: 30
      VpcConfig:
        SubnetIds:
          - subnet-0489ad25a0190cb33
          - subnet-0685b5b91da395f24
          - subnet-0f75b0df849c129a5
          - subnet-0d5602d623280bbae
          - subnet-0f97e89ecb8a78721
          - subnet-05959e72acd6f038f
        SecurityGroupIds:
          - sg-09f6904876f01545b
          - sg-09335b86ed90e9083
          - sg-0401dffe58ec6bca9
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: "arn:aws:kms:us-east-1:038462753284:key/e7f712a6-2273-4cfb-a97b-e5eac6d64c68"
      Events:
        RDSAPI:
          Type: Api
          Properties:
            Path: /rds
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
